dependencies:
  build:
    - node:10.16.3

build_targets:
  - name: node_base
    commands:
      - npm install --no-optional
      - npm ci
      - npm run bootstrap
  - name: test_service
    build_after:
      - node_base
    environment:
      - CHOKIDAR_USEPOLLING="1"
      - DEBIAN_FRONTEND=noninteractive
    commands:
      - apt-get update -q
      - apt-get install -yq rsync
      - git config --global user.name "Garden CI"
      - git config --global user.email "admin@garden.io"
      - cd garden-service
      - npm install
      - npm test

ci:
  builds:
    - name: test_service
      build_target: test_service
