dependencies:
  build:
    - node:10.16.3

build_targets:
  - name: node_base
    commands:
      - npm install -g npm@latest
      - npm install --no-optional
      - npm install lerna -g
      - npm run bootstrap
      - npm ci
